export { default as About } from "./about";
export { default as Contact } from "./contact";
export { default as Experience } from "./experience";
export { default as Footer } from "./footer";
export { default as Header } from "./header";
export { default as Nav } from "./nav";
export { default as Portfolio } from "./portfolio";
export { default as Services } from "./services";
export { default as Testimonials } from "./testimonials";
